import 'package:micro_opportunites/dev/fake_api/fake_database.dart';

/// Horaires relatifs à « maintenant », exprimés à l'heure du Bénin.
class _SeedTime {
  _SeedTime(DateTime now) : _now = now.toUtc();

  final DateTime _now;

  /// Jour J+[days] à [hour]:[minute] (heure du Bénin) → ISO UTC.
  String at(int days, int hour, [int minute = 0]) {
    final benin = _now.add(const Duration(hours: 1));
    final local = DateTime.utc(
      benin.year,
      benin.month,
      benin.day + days,
      hour,
      minute,
    );
    return local.subtract(const Duration(hours: 1)).toIso8601String();
  }

  String ago(Duration duration) => _now.subtract(duration).toIso8601String();

  String later(Duration duration) => _now.add(duration).toIso8601String();
}

/// Base de démonstration fidèle aux planches B01–B17.
FakeDatabase seedDatabase(DateTime now) {
  final t = _SeedTime(now);
  final db = FakeDatabase(currentUserId: 'u1');

  db.users['u1'] = {
    'id': 'u1',
    'firstName': 'Rodrigue',
    'lastName': 'K.',
    'city': 'Abomey-Calavi',
    'lat': 6.4485,
    'lng': 2.3557,
    'payoutAccount': {
      'operator': 'MTN MoMo',
      'maskedNumber': '01 97 •• •• 45',
      'holderName': 'Rodrigue K.',
    },
  };

  db.posters['p1'] = {
    'id': 'p1',
    'displayName': 'Adjovi H.',
    'initials': 'AH',
    'verified': true,
    'reliable': true,
    'city': 'Abomey-Calavi',
    'memberSince': t.ago(const Duration(days: 200)),
    'rating': 4.8,
    'reviewsCount': 23,
    'paidMissions': 12,
    'avgValidationHours': 3,
    'reviews': [
      {
        'authorName': 'Mireille A.',
        'stars': 5,
        'comment': 'Consignes claires, accueil sympa, payée le jour même.',
        'context': 'Aide lors d’un événement',
        'date': t.ago(const Duration(days: 20)),
        'reply': null,
      },
      {
        'authorName': 'Serge T.',
        'stars': 4,
        'comment': 'Lieu un peu difficile à trouver, mais le repère aidait.',
        'context': 'Distribution de flyers',
        'date': t.ago(const Duration(days: 45)),
        'reply': 'Merci, j’ai ajouté une photo de l’entrée.',
      },
    ],
  };
  db.posters['p2'] = {
    'id': 'p2',
    'displayName': 'Koffi D.',
    'initials': 'KD',
    'verified': true,
    'reliable': false,
    'city': 'Abomey-Calavi',
    'memberSince': t.ago(const Duration(days: 90)),
    'rating': 4.6,
    'reviewsCount': 9,
    'paidMissions': 5,
    'avgValidationHours': 6,
    'reviews': [
      {
        'authorName': 'Aïcha B.',
        'stars': 5,
        'comment': 'Très clair sur ce qu’il fallait faire.',
        'context': 'Installation informatique',
        'date': t.ago(const Duration(days: 30)),
        'reply': null,
      },
    ],
  };
  db.posters['p3'] = {
    'id': 'p3',
    'displayName': 'Chantal A.',
    'initials': 'CA',
    'verified': true,
    'reliable': true,
    'city': 'Cotonou',
    'memberSince': t.ago(const Duration(days: 400)),
    'rating': 4.9,
    'reviewsCount': 15,
    'paidMissions': 8,
    'avgValidationHours': 2,
    'reviews': [
      {
        'authorName': 'Luc H.',
        'stars': 5,
        'comment': 'Paiement rapide, mission bien décrite.',
        'context': 'Saisie de données',
        'date': t.ago(const Duration(days: 12)),
        'reply': null,
      },
    ],
  };

  Json mission({
    required String id,
    required String title,
    required String category,
    required String city,
    required double lat,
    required double lng,
    required String startAt,
    required int durationMin,
    required int pay,
    required int slotsTotal,
    required int slotsFree,
    required String posterId,
    required String publishedAt,
    required String applyDeadline,
    required String description,
    required Json private,
    String status = 'published',
    int publicQuestionsCount = 0,
  }) => {
    'id': id,
    'title': title,
    'category': category,
    'city': city,
    'zone': {'lat': lat, 'lng': lng},
    'startAt': startAt,
    'durationMin': durationMin,
    'pay': {'amount': pay, 'type': 'flat'},
    'slotsTotal': slotsTotal,
    'slotsFree': slotsFree,
    'posterId': posterId,
    'publishedAt': publishedAt,
    'applyDeadline': applyDeadline,
    'description': description,
    'status': status,
    'publicQuestionsCount': publicQuestionsCount,
    'private': private,
  };

  for (final m in [
    mission(
      id: 'm1',
      title: 'Distribution de flyers au carrefour',
      category: 'event',
      city: 'Abomey-Calavi',
      lat: 6.4550,
      lng: 2.3450,
      startAt: t.at(4, 8),
      durationMin: 240,
      pay: 5000,
      slotsTotal: 5,
      slotsFree: 3,
      posterId: 'p1',
      publishedAt: t.ago(const Duration(minutes: 20)),
      applyDeadline: t.at(3, 18),
      description:
          'Distribuer 500 flyers pour l’ouverture d’une boutique. Flyers et t-shirt fournis.',
      publicQuestionsCount: 2,
      private: {
        'district': 'Zogbadjè',
        'address': 'Zogbadjè, carrefour Kpota',
        'landmark': 'Face à la pharmacie Kpota, boutique à façade verte.',
        'lat': 6.4552,
        'lng': 2.3452,
        'briefing': '500 flyers · t-shirt fourni',
      },
    ),
    mission(
      id: 'm2',
      title: 'Réinstaller Windows sur un portable',
      category: 'computer',
      city: 'Abomey-Calavi',
      lat: 6.4400,
      lng: 2.3600,
      startAt: t.at(1, 10),
      durationMin: 120,
      pay: 7500,
      slotsTotal: 1,
      slotsFree: 1,
      posterId: 'p2',
      publishedAt: t.ago(const Duration(hours: 1)),
      applyDeadline: t.at(0, 21),
      description:
          'Réinstaller Windows 11 et les logiciels de base sur un portable HP. Clé USB fournie.',
      private: {
        'district': 'Tankpè',
        'address': 'Tankpè, rue des Écoles',
        'landmark':
            'Maison à portail noir après la boulangerie. Demandez Koffi.',
        'lat': 6.4402,
        'lng': 2.3602,
        'briefing': 'Portable HP · clé USB fournie',
      },
    ),
    mission(
      id: 'm3',
      title: 'Courses au marché',
      category: 'shopping',
      city: 'Cotonou',
      lat: 6.3703,
      lng: 2.3912,
      startAt: t.at(2, 9),
      durationMin: 90,
      pay: 3000,
      slotsTotal: 1,
      slotsFree: 1,
      posterId: 'p3',
      publishedAt: t.ago(const Duration(hours: 20)),
      applyDeadline: t.at(1, 20),
      description: 'Faire les courses de la semaine au marché, liste fournie.',
      private: {
        'district': 'Saint-Michel',
        'address': 'Saint-Michel, rue 12',
        'landmark': 'Immeuble jaune en face de l’église.',
        'lat': 6.3705,
        'lng': 2.3915,
        'briefing': 'Liste et argent fournis',
      },
    ),
    mission(
      id: 'm4',
      title: 'Nettoyage de bureau',
      category: 'cleaning',
      city: 'Cotonou',
      lat: 6.3650,
      lng: 2.4180,
      startAt: t.at(6, 8),
      durationMin: 180,
      pay: 7500,
      slotsTotal: 2,
      slotsFree: 2,
      posterId: 'p2',
      publishedAt: t.ago(const Duration(days: 3)),
      applyDeadline: t.at(5, 18),
      description:
          'Nettoyer un bureau de 60 m² après travaux. Produits fournis.',
      private: {
        'district': 'Ganhi',
        'address': 'Ganhi, avenue Clozel',
        'landmark': 'Deuxième étage au-dessus de la banque.',
        'lat': 6.3652,
        'lng': 2.4182,
        'briefing': 'Produits fournis',
      },
    ),
    mission(
      id: 'm5',
      title: 'Aide au service lors d’un mariage',
      category: 'event',
      city: 'Abomey-Calavi',
      lat: 6.4600,
      lng: 2.3500,
      startAt: t.at(11, 11),
      durationMin: 360,
      pay: 10000,
      slotsTotal: 4,
      slotsFree: 4,
      posterId: 'p1',
      publishedAt: t.ago(const Duration(days: 2)),
      applyDeadline: t.at(9, 18),
      description:
          'Servir les boissons et le repas pour 150 invités. Tenue fournie.',
      private: {
        'district': 'Akassato',
        'address': 'Akassato, salle des fêtes Le Palmier',
        'landmark': 'Grand portail blanc sur la voie pavée.',
        'lat': 6.4602,
        'lng': 2.3502,
        'briefing': 'Tenue fournie · repas offert',
      },
    ),
    mission(
      id: 'm6',
      title: 'Saisie de fiches clients',
      category: 'data_entry',
      city: 'Abomey-Calavi',
      lat: 6.4450,
      lng: 2.3700,
      startAt: t.at(3, 9),
      durationMin: 240,
      pay: 6000,
      slotsTotal: 2,
      slotsFree: 1,
      posterId: 'p3',
      publishedAt: t.ago(const Duration(hours: 5)),
      applyDeadline: t.at(2, 18),
      description:
          'Saisir 200 fiches clients dans un tableur. Ordinateur fourni.',
      private: {
        'district': 'Arconville',
        'address': 'Arconville, rue du Lycée',
        'landmark': 'Cyber café à l’angle, entrée latérale.',
        'lat': 6.4452,
        'lng': 2.3702,
        'briefing': 'Ordinateur fourni',
      },
    ),
    mission(
      id: 'm7',
      title: 'Livraison de colis au campus',
      category: 'delivery',
      city: 'Abomey-Calavi',
      lat: 6.4200,
      lng: 2.3400,
      startAt: t.at(0, 15),
      durationMin: 120,
      pay: 2500,
      slotsTotal: 3,
      slotsFree: 2,
      posterId: 'p2',
      publishedAt: t.ago(const Duration(hours: 2)),
      applyDeadline: t.at(0, 13),
      description:
          'Livrer 12 colis aux résidences universitaires. Moto non nécessaire.',
      private: {
        'district': 'Campus',
        'address': 'Campus d’Abomey-Calavi, entrée principale',
        'landmark': 'Kiosque de la porte principale.',
        'lat': 6.4202,
        'lng': 2.3402,
        'briefing': '12 colis',
      },
    ),
    mission(
      id: 'm8',
      title: 'Réparation d’une chaise',
      category: 'repair',
      city: 'Abomey-Calavi',
      lat: 6.4520,
      lng: 2.3650,
      startAt: t.at(2, 16),
      durationMin: 60,
      pay: 2000,
      slotsTotal: 1,
      slotsFree: 1,
      posterId: 'p3',
      publishedAt: t.ago(const Duration(days: 1)),
      applyDeadline: t.at(1, 18),
      description: 'Recoller et renforcer une chaise en bois.',
      private: {
        'district': 'Houèto',
        'address': 'Houèto, von de l’école',
        'landmark': 'Maison bleue après le puits.',
        'lat': 6.4522,
        'lng': 2.3652,
        'briefing': 'Outils à apporter',
      },
    ),
    mission(
      id: 'm9',
      title: 'Distribution de flyers au marché Dantokpa',
      category: 'flyers',
      city: 'Cotonou',
      lat: 6.3730,
      lng: 2.4290,
      startAt: t.at(4, 8),
      durationMin: 240,
      pay: 4000,
      slotsTotal: 4,
      slotsFree: 3,
      posterId: 'p1',
      publishedAt: t.ago(const Duration(hours: 4)),
      applyDeadline: t.at(3, 18),
      description:
          'Distribuer des flyers d’une nouvelle pharmacie aux entrées du marché.',
      private: {
        'district': 'Dantokpa',
        'address': 'Marché Dantokpa, entrée nord',
        'landmark': 'Sous le panneau de la pharmacie.',
        'lat': 6.3732,
        'lng': 2.4292,
        'briefing': '1 000 flyers',
      },
    ),
    mission(
      id: 'm10',
      title: 'Inventaire de boutique',
      category: 'data_entry',
      city: 'Ouidah',
      lat: 6.3667,
      lng: 2.0850,
      startAt: t.at(8, 9),
      durationMin: 300,
      pay: 15000,
      slotsTotal: 2,
      slotsFree: 2,
      posterId: 'p3',
      publishedAt: t.ago(const Duration(days: 2)),
      applyDeadline: t.at(6, 18),
      description: 'Compter et saisir le stock d’une boutique de tissus.',
      private: {
        'district': 'Centre',
        'address': 'Ouidah, rue du Fort',
        'landmark': 'Boutique Tissus Élégance.',
        'lat': 6.3669,
        'lng': 2.0852,
        'briefing': 'Tablette fournie',
      },
    ),
    mission(
      id: 'm11',
      title: 'Nettoyage après un événement',
      category: 'cleaning',
      city: 'Abomey-Calavi',
      lat: 6.4380,
      lng: 2.3480,
      startAt: t.at(1, 18),
      durationMin: 180,
      pay: 5000,
      slotsTotal: 3,
      slotsFree: 3,
      posterId: 'p1',
      publishedAt: t.ago(const Duration(hours: 8)),
      applyDeadline: t.at(1, 12),
      description: 'Ranger et nettoyer une salle après une conférence.',
      private: {
        'district': 'Kpota',
        'address': 'Kpota, salle polyvalente',
        'landmark': 'Derrière le terrain de foot.',
        'lat': 6.4382,
        'lng': 2.3482,
        'briefing': 'Gants fournis',
      },
    ),
    mission(
      id: 'm12',
      title: 'Installation d’une imprimante',
      category: 'computer',
      city: 'Cotonou',
      lat: 6.3600,
      lng: 2.4000,
      startAt: t.at(0, 17),
      durationMin: 60,
      pay: 3500,
      slotsTotal: 1,
      slotsFree: 1,
      posterId: 'p2',
      publishedAt: t.ago(const Duration(minutes: 30)),
      applyDeadline: t.at(0, 15),
      description: 'Installer une imprimante Wi-Fi sur deux ordinateurs.',
      private: {
        'district': 'Cadjèhoun',
        'address': 'Cadjèhoun, rue 1024',
        'landmark': 'Immeuble à côté de la station.',
        'lat': 6.3602,
        'lng': 2.4002,
        'briefing': 'Imprimante neuve',
      },
    ),
    mission(
      id: 'm13',
      title: 'Accueil des invités à un salon',
      category: 'event',
      city: 'Abomey-Calavi',
      lat: 6.4130,
      lng: 2.3250,
      startAt: t.at(0, 11),
      durationMin: 240,
      pay: 5000,
      slotsTotal: 1,
      slotsFree: 0,
      posterId: 'p1',
      publishedAt: t.ago(const Duration(days: 6)),
      applyDeadline: t.at(-1, 18),
      description:
          'Accueillir et orienter les invités d’un salon professionnel.',
      status: 'filled',
      private: {
        'district': 'Godomey',
        'address': 'Godomey, rue de la pharmacie',
        'landmark':
            'Face à la station du carrefour, portail bleu. Demandez Adjovi à l’entrée.',
        'lat': 6.4135,
        'lng': 2.3280,
        'briefing': 'Badge et t-shirt fournis',
      },
    ),
    mission(
      id: 'm14',
      title: 'Service traiteur pour un baptême',
      category: 'event',
      city: 'Cotonou',
      lat: 6.3650,
      lng: 2.4100,
      startAt: t.at(-2, 12),
      durationMin: 300,
      pay: 8000,
      slotsTotal: 2,
      slotsFree: 0,
      posterId: 'p3',
      publishedAt: t.ago(const Duration(days: 10)),
      applyDeadline: t.at(-4, 18),
      description: 'Servir le buffet d’un baptême.',
      status: 'filled',
      private: {
        'district': 'Fidjrossè',
        'address': 'Fidjrossè, plage',
        'landmark': 'Paillote rouge.',
        'lat': 6.3652,
        'lng': 2.4102,
        'briefing': 'Tenue noire',
      },
    ),
    mission(
      id: 'm15',
      title: 'Tri de documents',
      category: 'data_entry',
      city: 'Abomey-Calavi',
      lat: 6.4500,
      lng: 2.3600,
      startAt: t.at(-5, 9),
      durationMin: 180,
      pay: 4000,
      slotsTotal: 1,
      slotsFree: 1,
      posterId: 'p2',
      publishedAt: t.ago(const Duration(days: 14)),
      applyDeadline: t.at(-7, 18),
      description: 'Classer des archives papier.',
      status: 'expired',
      private: {
        'district': 'Tankpè',
        'address': 'Tankpè, rue des Écoles',
        'landmark': 'Maison à portail noir.',
        'lat': 6.4502,
        'lng': 2.3602,
        'briefing': 'Boîtes fournies',
      },
    ),
  ]) {
    db.missions[m['id'] as String] = m;
  }

  Json application(
    String id,
    String missionId,
    String status,
    String createdAt, {
    String message = '',
    String? offerExpiresAt,
    String? assignmentId,
  }) => {
    'id': id,
    'missionId': missionId,
    'workerId': 'u1',
    'status': status,
    'message': message,
    'createdAt': createdAt,
    'offerExpiresAt': offerExpiresAt,
    'assignmentId': assignmentId,
  };

  for (final a in [
    application(
      'a1',
      'm2',
      'offered',
      t.ago(const Duration(days: 1)),
      message: 'Je suis disponible demain matin.',
      offerExpiresAt: t.later(const Duration(hours: 11)),
    ),
    application(
      'a2',
      'm13',
      'confirmed',
      t.ago(const Duration(days: 3)),
      assignmentId: 'as1',
    ),
    application('a3', 'm4', 'pending', t.ago(const Duration(hours: 5))),
    application('a4', 'm5', 'pending_sync', t.ago(const Duration(minutes: 10))),
    application('a5', 'm14', 'rejected', t.ago(const Duration(days: 8))),
    application('a6', 'm15', 'expired', t.ago(const Duration(days: 12))),
  ]) {
    db.applications[a['id'] as String] = a;
  }

  final m13 = db.missions['m13']!;
  final m13Private = m13['private'] as Json;
  db.assignments['as1'] = {
    'id': 'as1',
    'missionId': 'm13',
    'applicationId': 'a2',
    'workerId': 'u1',
    'title': m13['title'],
    'status': 'confirmed',
    'startAt': m13['startAt'],
    'durationMin': m13['durationMin'],
    'payAmount': 5000,
    'city': m13['city'],
    'district': m13Private['district'],
    'address': m13Private['address'],
    'landmark': m13Private['landmark'],
    'lat': m13Private['lat'],
    'lng': m13Private['lng'],
    'briefing': m13Private['briefing'],
    'posterName': 'Adjovi H.',
    'payoutOperator': 'MTN MoMo',
    'checkInAt': null,
    'checkInDistanceM': null,
    'checkOutAt': null,
    'note': null,
    'photos': <String>[],
    'autoValidateAt': null,
  };

  Json payout(
    String id,
    String title,
    String posterName,
    int amount,
    Duration ago,
    String reference,
  ) => {
    'id': id,
    'amount': amount,
    'grossAmount': amount,
    'missionTitle': title,
    'posterName': posterName,
    'validatedAt': t.ago(ago),
    'commissionLabel': '[à définir]',
    'accountLabel': 'MTN MoMo · •• 45',
    'reference': reference,
    'status': 'paid',
  };

  for (final p in [
    payout(
      'po1',
      'Configurer une box internet',
      'Koffi D.',
      7500,
      const Duration(days: 3),
      'MO-2026-004812',
    ),
    payout(
      'po2',
      'Saisie de questionnaires',
      'Chantal A.',
      6000,
      const Duration(days: 5),
      'MO-2026-004655',
    ),
    payout(
      'po3',
      'Livraison de repas',
      'Adjovi H.',
      4500,
      const Duration(days: 8),
      'MO-2026-004511',
    ),
    payout(
      'po4',
      'Indemnité d’annulation',
      'Adjovi H.',
      1000,
      const Duration(days: 11),
      'MO-2026-004420',
    ),
    payout(
      'po5',
      'Inventaire de stock',
      'Chantal A.',
      8000,
      const Duration(days: 15),
      'MO-2026-004302',
    ),
    payout(
      'po6',
      'Distribution de flyers',
      'Adjovi H.',
      5000,
      const Duration(days: 20),
      'MO-2026-004118',
    ),
  ]) {
    db.payouts[p['id'] as String] = p;
  }

  for (final alert in <Json>[
    {
      'id': 'al1',
      'keyword': null,
      'category': 'Informatique',
      'zone': 'Abomey-Calavi · 10 km',
      'minPay': 5000,
      'days': 'Tous les jours',
    },
    {
      'id': 'al2',
      'keyword': null,
      'category': 'Événement, Flyers',
      'zone': 'Cotonou et Calavi',
      'minPay': null,
      'days': 'Week-end seulement',
    },
    {
      'id': 'al3',
      'keyword': 'plomberie',
      'category': null,
      'zone': '5 km autour de moi',
      'minPay': null,
      'days': 'Tous les jours',
    },
  ]) {
    db.alerts[alert['id'] as String] = alert;
  }

  return db;
}
